### PR TITLE
Pass std::function by value in Node::Advertise and Node::Request

### LINKED ISSUE #203: Can't use auto when defining lambda function callbacks for methods like Node::Advertise
As the title states, when trying to call a method like [Advertise](https://ignitionrobotics.org/api/transport/9.0/classignition_1_1transport_1_1Node.html#a04d6c8e855cfdfe972e6399cc4e3a767) with a lambda function callback to create a service, the lambda function must be created before the `Advertise` method, and must also be fully defined - if the lambda function is created using type `auto`, then compilation fails when passing this lambda function into the `Advertise` method. An example can be found [here](https://github.com/ignitionrobotics/ign-gazebo/blob/a5abacfa74db6e8db0218bd32c55980e15cf249b/src/gui/Gui_TEST.cc#L53-L60).

### PR DESCRIPTION
**Pull request by Ryujiyasu**
# 🎉 New feature

Closes #203

## Summary

Applies the same approach as #382 (`Subscribe`) to the `Advertise` and `Request` methods, allowing users to pass capturing lambda callbacks directly without wrapping them in a `std::function` variable first.

- Changed `std::function` parameters from pass-by-reference to pass-by-value in `Node::Advertise` (2 overloads) and `Node::Request` (2 overloads)
- Used `std::move` to forward callbacks efficiently, consistent with #382
- Added 3 unit tests that pass capturing lambdas directly to `Advertise` and `Request`

## Test it

```bash
cd build
./bin/UNIT_Node_TEST --gtest_filter="*DirectLambda*"
```

Three new tests verify capturing lambdas work directly:
- `ServiceCallAsyncDirectLambda`
- `ServiceCallWithoutInputAsyncDirectLambda`
- `ServiceCallWithoutOutputAsyncDirectLambda`

## Checklist
- [x] Signed all commits for DCO
- [ ] Added a screen capture or video to the PR description that demonstrates the feature
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] Updated Bazel files (if adding new files). Created an issue otherwise.
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers
- [x] Was GenAI used to generate this PR? If so, make sure to add "Generated-by" to your commits. (See [this policy](https://osralliance.org/wp-content/uploads/2025/05/OSRF-Policy-on-the-Use-of-Generative-Tools-Generative-AI-in-Contributions.pdf) for more info.)

Generated-by: Claude Opus 4.6

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.

### CODE REVIEW

File: src/Node_TEST.cc [hunk 1]
```diff
@@ -1701,6 +1701,108 @@ TEST(NodeTest, ServiceCallWithoutOutputAsyncLambda)
...
+
+  reset();
+}
+
+//////////////////////////////////////////////////
+/// \brief Make an asynchronous service call without output passing a lambda
+/// directly (without pre-defining a std::function variable).
+TEST(NodeTest, ServiceCallWithoutOutputAsyncDirectLambda)
+{
+  bool executed = false;
```
Comment (caguero) [inline src/Node_TEST.cc]: Strictly speaking is not needed but for consistency and just in case we modify it in the future, can you add at the beginning and end the `reset()` calls?

File: include/gz/transport/detail/Node.hh
Comment (caguero) [inline include/gz/transport/detail/Node.hh]: I suggest to modify this line with:
```
return this->Advertise(_topic, std::move(f), _options);
```

**Review by caguero — COMMENTED** [review]
Thanks for the patch, looks a very good API improvement. I just suggested a few updates to entirely avoid any copies when using the lambda.

Besides the inline suggestions, could you also consider updating `RepHandler.hh::SetCallback()`:

```
public: void SetCallback(
std::function<bool(const Req &, Rep &)> _cb)
{
  this->cb = std::move(_cb);
}
```

There's also the Zenoh version, I suggest to pass by value as well.

And in `ReqHandler.hh::SetCallback()`:
```
public: void SetCallback(
std::function <void(const Rep &_rep, const bool _result)> _cb)
{
  this->cb = std::move(_cb);
}
```

**Review by caguero — COMMENTED** [review]
Could you also sign the commit?

File: include/gz/transport/detail/Node.hh [hunk 2]
```diff
@@ -345,13 +345,14 @@ namespace gz::transport
...
   {
     std::function<bool(const msgs::Empty &, ReplyT &)> f =
-      [_cb](const msgs::Empty &/*_internalReq*/, ReplyT &_internalRep)
+      [cb = std::move(_cb)](const msgs::Empty &/*_internalReq*/,
+                            ReplyT &_internalRep)
     {
-      return (_cb)(_internalRep);
+      return (cb)(_internalRep);
     };
     return this->Advertise(_topic, f, _options);
```
[the remark this answers is not in the document]
Comment (Ryujiyasu) [reply include/gz/transport/detail/Node.hh]: Done, updated to `std::move(f)`.

**Comment by Ryujiyasu** [comment]
Hi @azeey, the PR description already includes `Generated-by: Claude Opus 4.6` at the bottom, and all commits have the `Generated-by` and `Signed-off-by` lines in their messages. Please let me know if you'd like it in a different format or location.

**Review by caguero — APPROVED** [review]
Thanks for the patch!

**Comment by caguero** [comment]
@mergifyio backport gz-transport15 gz-transport14 gz-transport13 ign-transport11

**Comment by caguero** [comment]
@Ryujiyasu , we had to revert this patch because we ran into an issue compiling gz-sim. You can find more details in the rollback PR (#828). Feel free to explore some of the ideas discussed there and reopen it with some tests that trigger the overload ambiguity issue.
