### PR TITLE
Fix issue #468

### LINKED ISSUE #468: Service requester starting before responder causes timeout when both are in the same process
## Environment
* OS Version: Ubuntu 22.04
* Source or binary build? source, 764a04b

## Description
* Expected behavior: When the node of a service requester is started before the node of a responder, the service request should succeed as long as the responder is started before the requester's timeout.
* Actual behavior: Currently, if the requester and responder are in different processes, the expected behavior occurs, but if they are in the same process, the requester will always time out.

  
## Steps to reproduce

1. Checkout the `flaky_service` branch from https://github.com/azeey/gz-transport/
2. Build `examples/requester.cc` and run it.

The example shows that if the responder is started with a 2s delay in a separate thread, the request fails.

### PR DESCRIPTION
**Pull request by caguero**
# 🦟 Bug fix

Fixes #468 

## Summary

As described in issue #468, the case of a `Request()` before an `Advertise()` when both calls are within the same process wasn't considered. This patch makes it work as in the case where requester and responser are in different processes (which was already working).

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by iche033 — APPROVED** [review]

File: include/gz/transport/Discovery.hh [hunk 1]
```diff
@@ -317,6 +317,9 @@ namespace gz
             return false;
         }
 
+        if (this->connectionCb)
+          this->connectionCb(_publisher);
```
Comment (azeey) [inline include/gz/transport/Discovery.hh:321]: This fixes the test case for me, but would it handle a possible race condition where the requester makes the request right after this line executes?

Comment (caguero) [reply include/gz/transport/Discovery.hh]: I've included the callback within the `lock_guard` for consistency with the `Discover()` function. [ec324d2](https://github.com/gazebosim/gz-transport/pull/470/commits/ec324d2577ecc37cf07b29dd01876f8d36eeb29a)

**Review by azeey — APPROVED** [review]
