### PR TITLE
Fix flakiness in the TopicInfo test

### LINKED ISSUE #510: :farmer: Gz-transport11-homebrew `UNIT_gz_TEST ignTest.TopicInfo` failed
## Environment
* OS Version: MacOS
* Source build

## Steps to reproduce
1. Run a build in [gz-transport11](https://build.osrfoundation.org/job/gz_transport-ci-ign-transport11-homebrew-amd64/)
2. See `ignTest.TopicInfo` fail

## Output

Reference build: https://build.osrfoundation.org/job/gz_transport-ci-ign-transport11-homebrew-amd64/59/consoleFull

Log output:
```
33: [ RUN      ] ignTest.TopicInfo
33: /Users/jenkins/jenkins-agent/workspace/gz_transport-ci-ign-transport11-homebrew-amd64/gz-transport/src/cmd/gz_TEST.cc:135: Failure
33: Value of: infoFound
33:   Actual: false
33: Expected: true
33: OUTPUT[No publishers on topic [/foo]
33: ] Size[30]. Expected Size=50
33: 
33: /Users/jenkins/jenkins-agent/workspace/gz_transport-ci-ign-transport11-homebrew-amd64/gz-transport/src/cmd/gz_TEST.cc:138: Failure
33: Value of: output.find("ignition.msgs.Vector3d") != std::string::npos
33:   Actual: false
33: Expected: true
33: [  FAILED  ] ignTest.TopicInfo (26598 ms)
```

Might be related to #509

### PR DESCRIPTION
**Pull request by azeey**
# 🦟 Bug fix

Fixes #510 

## Summary
The flakiness appears to be a timing issue. The fix here involves running the loop that waits for the input messages in a separate thread before starting the publisher.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

File: src/cmd/gz_TEST.cc [hunk 1]
```diff
@@ -115,23 +116,29 @@ TEST(ignTest, TopicInfo)
...
+    {
+      std::cout << "Waiting for topic ...\n";
+      output = custom_exec_str(ign + " topic -t /foo -i " + g_ignVersion);
+      infoFound = output.size() > 50u;
+      std::this_thread::sleep_for(std::chrono::milliseconds(300));
+    }
+  });
+
+  std::this_thread::sleep_for(std::chrono::seconds(1));
+  std::cout << "Fork and run " << publisher_path << std::endl;
```
Comment (ahcorde) [inline src/cmd/gz_TEST.cc:137]: remove ?

**Review by ahcorde — CHANGES_REQUESTED** [review]

File: src/cmd/gz_TEST.cc (hunk 1 above)
Comment (azeey) [reply src/cmd/gz_TEST.cc]: Done in https://github.com/gazebosim/gz-transport/pull/551/commits/c58505382b1d2173019ed7ab1f60541f031d1ae5

**Comment by azeey** [comment]
Homebrew CI has run 3 times without any failures:
* https://build.osrfoundation.org/job/gz_transport-ci-pr_any-homebrew-amd64/200/
* https://build.osrfoundation.org/job/gz_transport-ci-pr_any-homebrew-amd64/201/
* https://build.osrfoundation.org/job/gz_transport-ci-pr_any-homebrew-amd64/202/

**Review by caguero — APPROVED** [review]

**Review by ahcorde — APPROVED** [review]
